# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.ms.netease.com/commonlibraryios/podspec.git'
source 'https://git.ms.netease.com/Three/netease-nsip-specs.git'

target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo
 pod 'React', :path => '../../../node_modules/react-native’, :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTActionSheet',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTLinkingIOS',
    'ART',
    'jschelpers_legacy',
    'cxxreact_legacy',
    'BatchedBridge'
 ]
 pod "Yoga", :path => “../../../node_modules/react-native/ReactCommon/yoga"


end
